title: "Liam McKay"
description: "Music, Code, and Video Portfolio"
url: "https://liammckay19.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty

social:
  instagram: "https://instagram.com/liammckaydrums"
  linkedin: "https://linkedin.com/in/liam-mckay-202020"
  facebook: "https://facebook.com/liammckaydrums"
  linktree: "https://linktr.ee/liammckaydrums"
  
collections:
  music:
    output: true
    permalink: /music/:name/

  projects:
    output: true
    permalink: /projects/:name/

  videos:
    output: true
    permalink: /videos/:name/

  visualart:
    output: true
    permalink: /visualart/:name/